version: '3'
services:
  postgreSql:
    container_name: RestaurantDB
    image: postgres:15
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Anant
      POSTGRES_PASSWORD: anant123 
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 300M

volumes:
  my_postgres_data:


