server:
  port: 9090

spring:
  application:
    name: Restaurant-App

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: Anant
    password: anant123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
